jamiesonreinhard/rails-superhero-for-rent

app/controllers/superheros_controller.rb, app/models/superhero.rb, app/models/user.rb, app/views/superheros/index.html.erb, config/routes.rb, db/migrate/20200818161903_create_superheros.rb, db/schema.rb, test/controllers/superheros_controller_test.rb, test/models/superhero_test.rb
Worked in team creating superhero model. Implemented routes with resources. Created superhero controller with actions. We did an initial mess with creating the model but corrected it.
=> Completed superhero model, routes and controller

app/assets/stylesheets/components/_carousel.scss, app/assets/stylesheets/pages/_show.scss, app/views/superheros/show.html.erb
looks great! we can go back and match up our fonts, styling so they are consistent later
=> show page carousel, headers and description complete

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_bg-video.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
home page now has video background, title and subtitle centered, and search bars and submit button
=> Homepage Updates

app/views/shared/_navbar.html.erb
Updated navbar and created links to home, all superheroes, and tested the logout and login again.
Only non-working link on navbar is for dashboard, which we'll fix tomorrow when we create the model for bookings and the dashboard view
=> Navbar updates

db/seeds.rb
I added some code in the seeding file but its not quite working yet.
Maybe we should use faker for the addresses also. The api also doesn't have a "superpower" attribute, so we could change that column in or db to "Power score" or something like that.
=> Superheroapi seeding

db/migrate/20200819175428_add_img_to_superheros.rb, db/schema.rb
Added image_url column to superheros
=> upadated schema

Gemfile, Gemfile.lock, app/models/superhero.rb, db/seeds.rb
completed JSON api parse, still need to do an array of addresses in the seeds
=> completed JSON parse in the seeds

app/javascript/plugins/init-map.js
Now when you add a superhero there will be a marker added to the map on the index page
=> markers are working on the map

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/views/superheros/index.html.erb, app/views/superheros/show.html.erb
Updated fonts and styling on index and show, added links/buttons where needed.
Val - I replaced the hardcoded text for Superman since it would have been the same for every super hero. I also changed the background color (whitesmoke, not quite plain white but close), and some of your text wasn't rendering properly as Lato so I added some classes to fix it.
I think once we get rid of the carousel we can refactor this with bootstrap. I think easiest would just to be having two bootstrap columns (first one 7/12 screen width, for the picture and superhero details, and second one 5/12 screen width for the booking form).
I also added a "Back to all superheroes" button in the show, and I fixed the Book Now Links in the cards on Index so they take you to the show page.
Maybe we can add some more …
=> Styling updates and added/fixed links to get from page to page

app/assets/stylesheets/pages/_show.scss, app/views/superheros/show.html.erb, db/seeds.rb
updated see .attach method and changes in the show html
=> Show updates

app/views/superheros/_form.html.erb
=> added address field to form

db/schema.rb, db/seeds.rb
removed test code. For now only doing 25 superheroes since I decreased it due to broken url links in the API, these 25 worked so let's see how it works once we put all the code together.
=> seeds completed

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_index_card.scss, app/views/layouts/application.html.erb, app/views/superheros/index.html.erb
badass price chip added to the cards, image aspect ratio fixed, and added a footer
=> Footer and more card styling

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_show.scss, app/views/layouts/application.html.erb
made footer smaller and lighter - **still need to fix positioning** - also standardized photo size in show
=> Show photo styling, and footer updates

db/seeds.rb
change the range to 1..50, randomized the superheroes from the sample of 700
=> randomized and increased the num of the superheroes

app/views/superheros/show.html.erb, db/schema.rb
Added small feature for pics to center around the face in the show view.
=> Added cloudinary feature

app/controllers/superheros_controller.rb, app/views/pages/home.html.erb, db/seeds.rb
created the search bar by name and city, updated seeds
=> search bar completed, seeds updated

app/views/superheros/index.html.erb
=> fixed image tag code

db/schema.rb, db/seeds.rb
put the .attach code line back in the seed
=> should fix the seed bug

db/seeds.rb
added begin and rescue in the seeds to fix the errors from the API
=> begin rescue implemented in the seed

app/assets/stylesheets/pages/_show.scss, app/views/reviews/_form.html.erb, app/views/superheros/index.html.erb, app/views/superheros/show.html.erb
can now create reviews and see them on the show page. All reviews get averaged and the average score is also shown in two places on the show. I also fixed the search form on index so it is working now
=> Reviews show

app/assets/stylesheets/components/_footer.scss, app/views/layouts/application.html.erb
added footer icons, set the hover effect and moved the contents to the side
=> udpated footer icons

app/controllers/superheros_controller.rb, app/models/superhero.rb, app/views/superheros/_form.html.erb, app/views/superheros/show.html.erb, db/migrate/20200820185725_add_description_to_superheros.rb, db/schema.rb, db/seeds.rb
description field added to new superhero form, and now show page is showing the superhero description. the database is seeded with Lorem Ipsum text for seeded superheroes
=> Description Added to Show Page, column added to Superheroes model.

app/controllers/bookings_controller.rb, app/models/booking.rb, app/models/superhero.rb, app/models/user.rb, app/views/superheros/_form_booking.html.erb, config/routes.rb, db/migrate/20200820180427_create_bookings.rb, db/schema.rb, test/controllers/bookings_controller_test.rb, test/models/booking_test.rb
booking model and controller; missing form and actions and maybe routes
=> Created booking model and controller

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_show.scss, app/controllers/superheros_controller.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/superheros/show.html.erb
fixed footer and also fixed geocoder so markers are working on the index page
=> Footer and Map Markers Fixed

app/controllers/bookings_controller.rb, app/controllers/pages_controller.rb, app/views/bookings/_edit_booking.html.erb, app/views/bookings/edit.html.erb, app/views/bookings/index.html.erb, app/views/pages/confirm.html.erb, app/views/superheros/show.html.erb, config/routes.rb
created edit, created all my bookings page, fixed edit bug
=> created all bookings form and confirmation form

app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_show.scss, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, app/views/superheros/index.html.erb, app/views/superheros/show.html.erb
much better but not perfect. Tomorrow final touches!
=> Show fixes
